spring:
  data:
    rest:
      basePath: /data
  jackson:
    serialization:
      indent_output: true
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

security:
  oauth2:
    client:
      clientId: 141006a9a09aaab10a9f
      clientSecret: aa258cc8acdc3030562e535f7a31e422502d6e4d
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user

management:
  security:
    enabled: false
  info:
    git:
      mode: full

com:
  sksi:
    ecobee:
      ecobeeApiKey: ${ECOBEE_API_KEY}

logging:
  level:
    com: 'INFO'
    com.sksi: 'DEBUG'
    org: 'INFO'
    org.apache: 'INFO'
    org.hibernate: 'INFO'
    org.hibernate.SQL: 'DEBUG'
    org.springframework: 'INFO'
    org.springframework.env: 'INFO'
    org.springframework.security: 'DEBUG'
    org.springframework.cloud.sleuth: 'INFO'

---

spring:
  profiles: dev

com:
  sksi:
    ecobee:
      devUserName: kevin
      devMode: true

---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:15432/abtest
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    username: abtest
    password: abtest
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

---

spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

security:
  oauth2:
    client:
      clientId: 7577e035f2b7ee60f0b4
      clientSecret: 500dc439e224d27ff766052677e376027dea1d9d
