spring:
  data:
    rest:
      basePath: /data
  jackson:
    serialization:
      indent_output: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

management:
  security:
    enabled: false
  info:
    git:
      mode: full
